"""init listings + caches

Revision ID: 27b2a086786d
Revises: 
Create Date: 2026-05-10 16:39:02.561099

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27b2a086786d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('rate_uzs', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'fetched_at', name='uq_rate_code_at')
    )
    op.create_index(op.f('ix_currency_rates_code'), 'currency_rates', ['code'], unique=False)
    op.create_table('geocode_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_norm', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('matched_text', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geocode_cache_query_norm'), 'geocode_cache', ['query_norm'], unique=True)
    op.create_table('listings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_listing_id', sa.String(length=64), nullable=False),
    sa.Column('source_category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('language_detected', sa.String(length=8), nullable=True),
    sa.Column('summary_one_line', sa.Text(), nullable=True),
    sa.Column('price_raw', sa.String(length=64), nullable=True),
    sa.Column('currency_raw', sa.String(length=8), nullable=True),
    sa.Column('price_uzs', sa.BigInteger(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('is_first_floor', sa.Boolean(), nullable=True),
    sa.Column('bathroom_type', sa.String(length=16), nullable=True),
    sa.Column('is_furnished', sa.Boolean(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('search_type_listing', sa.String(length=32), nullable=True),
    sa.Column('gender_constraint_listing', sa.String(length=8), nullable=True),
    sa.Column('poster_role', sa.String(length=8), nullable=True),
    sa.Column('agent_fee_text', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('contact_phone_raw', sa.String(length=32), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('poster_id', sa.String(length=64), nullable=True),
    sa.Column('image_urls', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('image_phashes', sa.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('canonical_listing_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', name='uq_listings_source_url')
    )
    op.create_index(op.f('ix_listings_area'), 'listings', ['area'], unique=False)
    op.create_index(op.f('ix_listings_canonical_listing_id'), 'listings', ['canonical_listing_id'], unique=False)
    op.create_index(op.f('ix_listings_phone_hash'), 'listings', ['phone_hash'], unique=False)
    op.create_index('ix_listings_phone_hash_alive', 'listings', ['phone_hash'], unique=False, postgresql_where="state != 'dead'")
    op.create_index(op.f('ix_listings_posted_at'), 'listings', ['posted_at'], unique=False)
    op.create_index(op.f('ix_listings_poster_id'), 'listings', ['poster_id'], unique=False)
    op.create_index(op.f('ix_listings_price_uzs'), 'listings', ['price_uzs'], unique=False)
    op.create_index(op.f('ix_listings_risk_score'), 'listings', ['risk_score'], unique=False)
    op.create_index(op.f('ix_listings_rooms'), 'listings', ['rooms'], unique=False)
    op.create_index(op.f('ix_listings_source_listing_id'), 'listings', ['source_listing_id'], unique=False)
    op.create_index(op.f('ix_listings_state'), 'listings', ['state'], unique=False)
    op.create_index('ix_listings_state_active', 'listings', ['state'], unique=False, postgresql_where="state = 'active'")
    op.create_index(op.f('ix_listings_suppressed'), 'listings', ['suppressed'], unique=False)
    op.create_table('scrape_run_health',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('used_playwright_fallback', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_run_health_category'), 'scrape_run_health', ['category'], unique=False)
    op.create_index(op.f('ix_scrape_run_health_ts'), 'scrape_run_health', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_run_health_ts'), table_name='scrape_run_health')
    op.drop_index(op.f('ix_scrape_run_health_category'), table_name='scrape_run_health')
    op.drop_table('scrape_run_health')
    op.drop_index(op.f('ix_listings_suppressed'), table_name='listings')
    op.drop_index('ix_listings_state_active', table_name='listings', postgresql_where="state = 'active'")
    op.drop_index(op.f('ix_listings_state'), table_name='listings')
    op.drop_index(op.f('ix_listings_source_listing_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_rooms'), table_name='listings')
    op.drop_index(op.f('ix_listings_risk_score'), table_name='listings')
    op.drop_index(op.f('ix_listings_price_uzs'), table_name='listings')
    op.drop_index(op.f('ix_listings_poster_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_posted_at'), table_name='listings')
    op.drop_index('ix_listings_phone_hash_alive', table_name='listings', postgresql_where="state != 'dead'")
    op.drop_index(op.f('ix_listings_phone_hash'), table_name='listings')
    op.drop_index(op.f('ix_listings_canonical_listing_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_area'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_geocode_cache_query_norm'), table_name='geocode_cache')
    op.drop_table('geocode_cache')
    op.drop_index(op.f('ix_currency_rates_code'), table_name='currency_rates')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
