"""add_users_events

Revision ID: 71d0019968ac
Revises: 0a8e737074f5
Create Date: 2026-05-10 22:03:34.615736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '71d0019968ac'
down_revision: Union[str, Sequence[str], None] = '0a8e737074f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_kind'), 'events', ['kind'], unique=False)
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.Text(), nullable=True),
    sa.Column('search_type', sa.String(length=32), nullable=True),
    sa.Column('gender_pref', sa.String(length=8), nullable=True),
    sa.Column('agent_filter', sa.String(length=16), nullable=True),
    sa.Column('budget_min', sa.BigInteger(), nullable=True),
    sa.Column('budget_max', sa.BigInteger(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('areas', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('move_in_window', sa.String(length=16), nullable=True),
    sa.Column('commute_origin', sa.Text(), nullable=True),
    sa.Column('commute_origin_lat', sa.Float(), nullable=True),
    sa.Column('commute_origin_lng', sa.Float(), nullable=True),
    sa.Column('commute_max_minutes', sa.Integer(), nullable=True),
    sa.Column('commute_mode', sa.String(length=8), nullable=True),
    sa.Column('dealbreakers', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('dealbreaker_keywords', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('axis_priority', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tradeoff_hint_text', sa.Text(), nullable=True),
    sa.Column('unacceptable_text', sa.Text(), nullable=True),
    sa.Column('instant_reject_text', sa.Text(), nullable=True),
    sa.Column('preference_embedding', Vector(3072), nullable=True),
    sa.Column('negative_area_mask', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('distrust_set', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('seen_set', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('top_1pct_threshold', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_state'), 'users', ['state'], unique=False)
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_state'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_index(op.f('ix_events_kind'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
