"""add matches table

Revision ID: beee0bd92f29
Revises: 71d0019968ac
Create Date: 2026-05-11 22:40:48.713219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beee0bd92f29'
down_revision: Union[str, Sequence[str], None] = '71d0019968ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('delivered_via', sa.String(length=8), nullable=True),
    sa.Column('dislike_reason', sa.String(length=32), nullable=True),
    sa.Column('liked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disliked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chase_48h_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chase_48h_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chase_5d_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chase_5d_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_matches_user_listing')
    )
    op.create_index(op.f('ix_matches_listing_id'), 'matches', ['listing_id'], unique=False)
    op.create_index('ix_matches_pending_score', 'matches', ['state', 'score'], unique=False, postgresql_where="state = 'pending'")
    op.create_index(op.f('ix_matches_state'), 'matches', ['state'], unique=False)
    op.create_index('ix_matches_user_delivered', 'matches', ['user_id', 'delivered_via', 'created_at'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    op.create_index('ix_matches_user_state_score', 'matches', ['user_id', 'state', 'score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matches_user_state_score', table_name='matches')
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index('ix_matches_user_delivered', table_name='matches')
    op.drop_index(op.f('ix_matches_state'), table_name='matches')
    op.drop_index('ix_matches_pending_score', table_name='matches', postgresql_where="state = 'pending'")
    op.drop_index(op.f('ix_matches_listing_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
